# Generated by Django 5.1.2 on 2024-10-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_waypoint_waypoint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='waypoint_type',
            field=models.CharField(choices=[('pickup', 'pickup'), ('delivery', 'delivery')], max_length=20),
        ),
    ]
